# Generated by Django 3.2.3 on 2021-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=50)),
                ('coach', models.CharField(max_length=70)),
                ('p1', models.CharField(max_length=70)),
                ('p2', models.CharField(max_length=70)),
                ('p3', models.CharField(max_length=70)),
                ('p4', models.CharField(max_length=70)),
                ('p5', models.CharField(max_length=70)),
            ],
        ),
    ]
